---
- hosts: all
  become: yes
  become_user: root

  vars:
    helloworld: Meow!

  tasks:
    - name: ansible apt install apache2
      apt:
        name: apache2
        state: present

    - name: Configure Cat App
      template:
        src: index.j2
        dest: /var/www/html/index.html

    - name: Start the apache2 service
      service:
        name: apache2
        state: started

  handlers:
    - name: Restart apache2
      service:
        name: httpd
        state: restarted
